const bullishEngulfing = require('./bullishEngulfing');
const bearishEngulfing = require('./bearishEngulfing');
const hammer = require('./hammer');
const morningEveningStar = require('./morningEveningStar');
const shootingStar = require('./shootingStar');
const threeCandleReversal = require('./threeCandleReversal');
const wickBodyPattern = require('./wickBodyPattern');
const institutionalReversalTrap = require('./institutionalReversalTrap');
const utBotPattern = require('./utBotPattern');
const trendStrategy = require('./trendStrategy');
const meanReversion = require('./meanReversion');
const logger = require('../../utils/logger');


const path = require('path');
const patternsConfig = require('./patternsConfig.json');


function loadPatterns() {
  return patternsConfig.map(cfg => ({
    name: cfg.name,
    fn: require(path.join(__dirname, cfg.file)),
    value: cfg.value,

  }));
}

const allPatterns = loadPatterns();

function checkPatterns(candles) {
  for (const { name, fn } of allPatterns) {
    const result = fn(candles);
    if (result) {
      return { pattern: name, ...result };
    }
  }
  return null;
}


// need to switch based on pattern name with pattern return
function runPattern(patternName, candles, options = {}) {
  if (!patternName || !candles) {
    return null;
  };

  let result = null;

  switch (patternName) {
    case 'BLLENG':
      result = bullishEngulfing(candles, options);
      break;
    case 'HMMR':
      result = hammer(candles, options);
      break;
    case 'BRSHENG':
      result = bearishEngulfing(candles, options);
      break;
    case 'SHTNGSTR':
      result = shootingStar(candles, options);
      break;
    case 'MESTR':
      result = morningEveningStar(candles, options);
      break;
    case '3VRVRSL':
      result = threeCandleReversal(candles, options);
      break;
    case 'INSRVVL':
      result = institutionalReversalTrap(candles, options);
      break;
    case 'WICKBODY':
      result = wickBodyPattern(candles, options);
      break;
    case 'UTBOT':
      result = utBotPattern(candles, options);
      break;
    case 'TREND_FOLLOWING':
      result = trendStrategy(candles, options);
      break;
    case 'MEAN_REVERSION':
      result = meanReversion(candles, options);
      break;
    case 'GRID_RANGE':
      // Grid trades are generated by dedicated runtime engine.
      result = null;
      break;
    default:
      result = shootingStar(candles, options);
      break;

  }

  return result;

}


function availablePatterns() {
  return allPatterns;
}

module.exports = { checkPatterns, runPattern, availablePatterns };
