const bullishEngulfing = require('./bullishEngulfing');
const bearishEngulfing = require('./bearishEngulfing');
const hammer = require('./hammer');
const morningEveningStar = require('./morningEveningStar');
const shootingStar = require('./shootingStar');
const threeCandleReversal = require('./threeCandleReversal');
const wickBodyPattern = require('./wickBodyPattern');
const institutionalReversalTrap = require('./institutionalReversalTrap');
const utBotPattern = require('./utBotPattern');
const trendStrategy = require('./trendStrategy');
const meanReversion = require('./meanReversion');
const logger = require('../../utils/logger');


const path = require('path');
const patternsConfig = require('./patternsConfig.json');


function loadPatterns() {
  return patternsConfig.map(cfg => ({
    name: cfg.name,
    fn: require(path.join(__dirname, cfg.file)),
    value: cfg.value,

  }));
}

const allPatterns = loadPatterns();

function parseRewardMultiplier(riskRewardRatio) {
  if (typeof riskRewardRatio === 'number' && Number.isFinite(riskRewardRatio) && riskRewardRatio > 0) {
    return riskRewardRatio;
  }

  if (typeof riskRewardRatio === 'string') {
    const match = riskRewardRatio.match(/^\s*1\s*:\s*(\d+(?:\.\d+)?)\s*$/);
    if (match) {
      const parsed = Number(match[1]);
      if (Number.isFinite(parsed) && parsed > 0) return parsed;
    }
  }

  return null;
}

function applyRiskRewardOverride(result, riskRewardRatio) {
  if (!result) return result;

  const rewardMultiplier = parseRewardMultiplier(riskRewardRatio);
  if (!rewardMultiplier) return result;

  const entryPrice = Number(result.entryPrice);
  const stopLoss = Number(result.stopLoss);
  const signal = result.signal;

  if (!Number.isFinite(entryPrice) || !Number.isFinite(stopLoss)) return result;
  if (signal !== 'BUY' && signal !== 'SELL') return result;

  const riskDistance = Math.abs(entryPrice - stopLoss);
  if (!Number.isFinite(riskDistance) || riskDistance <= 0) return result;

  const takeProfit = signal === 'BUY'
    ? entryPrice + (riskDistance * rewardMultiplier)
    : entryPrice - (riskDistance * rewardMultiplier);

  return {
    ...result,
    takeProfit: Number(takeProfit.toFixed(5)),
    riskReward: `1:${rewardMultiplier}`,
  };
}

function checkPatterns(candles) {
  for (const { name, fn } of allPatterns) {
    const result = fn(candles);
    if (result) {
      return { pattern: name, ...result };
    }
  }
  return null;
}


// need to switch based on pattern name with pattern return
function runPattern(patternName, candles, options = {}) {
  if (!patternName || !candles) {
    return null;
  };

  let result = null;

  switch (patternName) {
    case 'BLLENG':
      result = bullishEngulfing(candles);
      break;
    case 'HMMR':
      result = hammer(candles);
      break;
    case 'BRSHENG':
      result = bearishEngulfing(candles);
      break;
    case 'SHTNGSTR':
      result = shootingStar(candles);
      break;
    case 'MESTR':
      result = morningEveningStar(candles);
      break;
    case '3VRVRSL':
      result = threeCandleReversal(candles);
      break;
    case 'INSRVVL':
      result = institutionalReversalTrap(candles);
      break;
    case 'WICKBODY':
      result = wickBodyPattern(candles);
      break;
    case 'UTBOT':
      result = utBotPattern(candles, options);
      break;
    case 'TREND_FOLLOWING':
      result = trendStrategy(candles, options);
      break;
    case 'MEAN_REVERSION':
      result = meanReversion(candles, options);
      break;
    case 'GRID_RANGE':
      // Grid trades are generated by dedicated runtime engine.
      result = null;
      break;
    default:
      result = shootingStar(candles);
      break;

  }

  return applyRiskRewardOverride(result, options.riskRewardRatio);

}


function availablePatterns() {
  return allPatterns;
}

module.exports = { checkPatterns, runPattern, availablePatterns };
